# Generated by Django 3.2.6 on 2021-08-19 20:00

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Account',
            fields=[
                ('address', models.CharField(max_length=128, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=128, unique=True)),
                ('ethers', models.IntegerField()),
                ('tokens', models.IntegerField()),
            ],
        ),
    ]
