# Generated by Django 3.2.6 on 2021-08-20 19:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contracts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='platform',
            field=models.CharField(default='ethereum', max_length=128),
            preserve_default=False,
        ),
    ]
